#include "text.h"

const char *text = "EVERY DAY, THE SUN RISES IN THE EAST AND SETS IN THE WEST. AT NIGHT, THE MOON TAKES ITS PLACE AND LIGHTS UP THE SKY. THEY NEVER MEET BUT ALWAYS FOLLOW EACH OTHER, BRINGING LIGHT TO THE WORLD.";
