#include "wordPool.h"

char* wordPool[POOL_SIZE] = {
    "THIS", "IS", "A", "TYPING", "TEST", "WITH", "MULTIPLE", "WORDS",
    "TO", "SIMULATE", "THE", "FUNCTIONALITY", "OF", "MONKEYTYPE",
    "YOU", "CAN", "ADD", "MORE", "WORDS", "AS", "NEEDED", "FOR", "TESTING",
    "PURPOSES", "AND", "TO", "SEE", "HOW", "THE", "PROGRAM", "WORKS",
    "EXAMPLE", "RANDOM", "SELECTION", "COMPUTER", "SCIENCE", "PROGRAMMING",
    "LANGUAGE", "KEYBOARD", "PRACTICE", "ACCURACY", "SPEED", "CHALLENGE",
    "IMPROVE", "SKILLS", "LEARNING", "DEVELOPMENT", "EXPERIENCE", "GOAL",
    "ACHIEVEMENT", "PROGRESS", "CONSISTENT", "EFFORT", "DEDICATION", "FOCUS",
    "TYPING", "TEST", "DYNAMIC", "UPDATE", "FUNCTION", "INITIALIZE",
    "HANDLE", "INPUT", "DISPLAY", "CURRENT", "STATE", "NEXT", "WORD",
    "CORRECT", "INCORRECT", "EXPECTED", "COMPARISON", "CHARACTER", "ADD",
    "POOL", "SIZE", "MEMORY", "ALLOCATION", "FREE", "CLEANUP", "COMPLETED"
};
