#define KBC_OUTPUT_BUFFER 0x60
#define KBC_STATUS_REGISTER 0x64


///KBC STATUS REGISTER
#define KBC_STATUS_PARITY BIT(7)
#define KBC_STATUS_TIMEOUT BIT(6)
#define KBC_STATUS_AUX BIT(5)
#define KBC_STATUS_INH BIT(4)
#define KBC_STATUS_SYS BIT(3)
#define KBC_STATUS_INPUT BIT(2)
#define KBC_STATUS_OUTPUT BIT(0)

#define BREAK_ESC 0x81

